### ISSUE TITLE
Update SEO description

### ISSUE THREAD

**Issue by mjovanc** [delta-rs/website#10]
Update it to: 

> Delta (Δ) is a high-performance machine learning framework written in Rust, tailored for compute-intensive tasks. Designed with both beginners and experts in mind, it offers intuitive APIs that simplify workflows while remaining flexible for advanced customizations.

![Screenshot 2024-12-17 at 11 45 19](https://github.com/user-attachments/assets/b9b6013d-bb0c-4357-a854-2276aece0565)

**Comment by SvMak** [comment]
If you feel the issue is not resolved, please reopen it.
