### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by chaseWillden** [delta-rs/website#15]
Most framework sites have super clear instructions on how to easily get started. Here's what I'd expect from the home page:
 - `cargo add deltaml`
 - Show super simple example on how to get started

**Comment by SvMak** [comment]
https://github.com/delta-rs/delta/blob/master/examples/image_classification/cifar10/src/main.rs As I understand it, we can take this as an example?

**Comment by mjovanc** [comment]
> https://github.com/delta-rs/delta/blob/master/examples/image_classification/cifar10/src/main.rs As I understand it, we can take this as an example?

Yes, that is a good way to demonstrate it. Take a look at this issue also: https://github.com/delta-rs/website/issues/18

**Comment by SvMak** [comment]
If you feel the issue is not resolved, please reopen it.
