### ISSUE TITLE
Add documentation on website

### ISSUE THREAD

**Issue by mjovanc** [delta-rs/website#18]
I think we should move the documentation from the Delta wiki to Delta website. This is the current Wiki: https://github.com/delta-rs/delta/wiki

My idea is that we move it there somehow. Also we need documentation for the Nebula project how to use it etc. It can be TBD there for now, but just so we have a place to add that documentation. 

I would like that in this repo we could write the documentation in Markdown if possible. 

I'm checking Tensorflows docs and it looks like this: https://www.tensorflow.org/tutorials which looks cool. And if we could Organize it somehow like this (not strict):

Delta
- Beginner
-- Some Topic
-- Some Other Topic
- Advanced
-- Some Topic
-- Some Other Topic

Nebula
- Beginner
-- Some Topic
-- Some Other Topic
- Advanced
-- Some Topic
-- Some Other Topic

We have two seperate projects on-going so it would be good to seperate them I believe like this.

What do you think of this @SvMak?

**Comment by mjovanc** [comment]
We should probably have on the landing page under the three boxes this information (will be added more later): https://github.com/delta-rs/delta/wiki/Getting-Started

**Comment by SvMak** [comment]
If you feel the issue is not resolved, please reopen it.
