### ISSUE TITLE
Change font to Chakra Petch if it looks good

### ISSUE THREAD

**Issue by mjovanc** [delta-rs/website#20]
Could we try switching to the font: Chakra Petch

<img width="208" alt="Screenshot 2024-12-21 at 10 53 52 AM" src="https://github.com/user-attachments/assets/93f1ff87-640d-46f9-a936-62e431906854" />

**Comment by SvMak** [comment]
If you feel the issue is not resolved or you prefer revert font to "Inter", please reopen it.
